version: "3"

services:
  app:
    build:
     context: .
    # map host - to image port
    ports:
      - "8000:8000"
    volumes:
    # map volumes
      - ./app:/app
    # run shell 
    # run django development server on all ip addresses on port 8000 ( mapped tp local machine)
    command: >
      sh -c  "python manage.py wait_for_db && 
              python manage.py migrate &&
              python manage.py runserver 0.0.0.0:8000"
    environment:
      - DB_HOST=db
      - DB_NAME=app
      - DB_USER=postgres
      - DB_PASS=supersecretpassword
    depends_on:
      - db

  db:
    image: postgres:10-alpine
    environment:
      - POSTGRES_DB=app
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=supersecretpassword
      # in prodction add a encryped env var that overwrites this 
      # when pushing 




# get the core 26.
# docker-compose run app sh -c "python manage.py startapp core"
